### ISSUE TITLE
Execution fails when using Firefox 50

### ISSUE THREAD

**Issue by sbathke** [automate-website/jwebrobot#53]
The following error occurred during running this command:

`$  java -jar jwebrobot-1.6.0.jar -scenarioPath ./payment.yaml -browser firefox`

```
2016-12-06 11:28:59,595 INFO [PatternScenarioLoader] - <Loaded 1 scenarios.>
2016-12-06 11:28:59,599 INFO [DefaultScenarioExecutor] - <Starting scenario Payment With CreditCard...>
org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","installDate":1479746003357,"updateDate":1479746003357,"applyBackgroundUpdates":1,"skinnable":true,"size":21146,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"50.0","maxVersion":"50.0"}],"targetPlatforms":[],"seen":true}
1481020141083   addons.xpi      DEBUG   getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1481020141083   DeferredSave.extensions.json    DEBUG   Save changes
1481020141083   addons.xpi      DEBUG   Updating database with changes to installed add-ons
1481020141083   addons.xpi-utils        DEBUG   Updating add-on states
1481020141085   addons.xpi-utils        DEBUG   Writing add-ons list
1481020141088   addons.xpi      DEBUG   Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\aushelper@mozilla.org.xpi
1481020141088   addons.xpi      DEBUG   Calling bootstrap method startup on aushelper@mozilla.org version 1.0
1481020141089   addons.xpi      DEBUG   Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1481020141089   addons.xpi      DEBUG   Calling bootstrap method startup on e10srollout@mozilla.org version 1.5
1481020141090   addons.xpi      DEBUG   Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1481020141090   addons.xpi      DEBUG   Calling bootstrap method startup on firefox@getpocket.com version 1.0.5
1481020141091   addons.xpi      DEBUG   Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\webcompat@mozilla.org.xpi
1481020141091   addons.xpi      DEBUG   Calling bootstrap method startup on webcompat@mozilla.org version 1.0
1481020141093   addons.manager  DEBUG   Registering shutdown blocker for XPIProvider
1481020141093   addons.manager  DEBUG   Provider finished startup: XPIProvider
1481020141093   addons.manager  DEBUG   Starting provider: LightweightThemeManager
1481020141094   addons.manager  DEBUG   Registering shutdown blocker for LightweightThemeManager
1481020141094   addons.manager  DEBUG   Provider finished startup: LightweightThemeManager
1481020141094   addons.manager  DEBUG   Starting provider: GMPProvider
1481020141100   addons.manager  DEBUG   Registering shutdown blocker for GMPProvider
1481020141101   addons.manager  DEBUG   Provider finished startup: GMPProvider
1481020141101   addons.manager  DEBUG   Starting provider: PluginProvider
1481020141101   addons.manager  DEBUG   Registering shutdown blocker for PluginProvider
1481020141101   addons.manager  DEBUG   Provider finished startup: PluginProvider
1481020141102   addons.manager  DEBUG   Completed startup sequence
[GFX1]: Potential driver version mismatch ignored due to missing DLLs 0.0.0.0 and 0.0.0.0
1481020141564   addons.manager  DEBUG   Starting provider: <unnamed-provider>
1481020141564   addons.manager  DEBUG   Registering shutdown blocker for <unnamed-provider>
1481020141564   addons.manager  DEBUG   Provider finished startup: <unnamed-provider>
1481020141566   DeferredSave.extensions.json    DEBUG   Starting write
1481020141730   addons.repository       DEBUG   No addons.json found.
1481020141730   DeferredSave.addons.json        DEBUG   Save changes
1481020141733   DeferredSave.addons.json        DEBUG   Starting timer
1481020141777   addons.manager  DEBUG   Starting provider: PreviousExperimentProvider
1481020141777   addons.manager  DEBUG   Registering shutdown blocker for PreviousExperimentProvider
1481020141777   addons.manager  DEBUG   Provider finished startup: PreviousExperimentProvider
1481020141779   DeferredSave.extensions.json    DEBUG   Write succeeded
1481020141779   addons.xpi-utils        DEBUG   XPI Database saved, setting schema version preference to 17
1481020141807   DeferredSave.addons.json        DEBUG   Starting write
1481020141818   DeferredSave.addons.json        DEBUG   Write succeeded
Crash Annotation GraphicsCriticalError: |[C0][GFX1]: Potential driver version mismatch ignored due to missing DLLs 0.0.0.0 and 0.0.0.0 (t=0.565463) [GFX1]: Potential driver version mismatch ignored due to missing DLLs 0.0.0.0 and 0.0.0.0

        at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:113)
        at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:271)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:119)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:216)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:211)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:207)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:120)
        at website.automate.jwebrobot.executor.WebDriverProvider.createInstance(WebDriverProvider.java:15)
        at website.automate.jwebrobot.executor.DefaultScenarioExecutor.execute(DefaultScenarioExecutor.java:86)
        at website.automate.jwebrobot.executor.DefaultScenarioExecutor.execute(DefaultScenarioExecutor.java:71)
        at website.automate.jwebrobot.JWebRobot.run(JWebRobot.java:37)
        at website.automate.jwebrobot.JWebRobot.main(JWebRobot.java:54)
Exception in thread "main" org.openqa.selenium.WebDriverException: Failed to connect to binary FirefoxBinary(C:\Program Files (x86)\Mozilla Firefox\firefox.exe) on port 7055; process output follows:
ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","installDate":1479746003357,"updateDate":1479746003357,"applyBackgroundUpdates":1,"skinnable":true,"size":21146,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"50.0","maxVersion":"50.0"}],"targetPlatforms":[],"seen":true}
1481020141083   addons.xpi      DEBUG   getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1481020141083   DeferredSave.extensions.json    DEBUG   Save changes
1481020141083   addons.xpi      DEBUG   Updating database with changes to installed add-ons
1481020141083   addons.xpi-utils        DEBUG   Updating add-on states
1481020141085   addons.xpi-utils        DEBUG   Writing add-ons list
1481020141088   addons.xpi      DEBUG   Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\aushelper@mozilla.org.xpi
1481020141088   addons.xpi      DEBUG   Calling bootstrap method startup on aushelper@mozilla.org version 1.0
1481020141089   addons.xpi      DEBUG   Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1481020141089   addons.xpi      DEBUG   Calling bootstrap method startup on e10srollout@mozilla.org version 1.5
1481020141090   addons.xpi      DEBUG   Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1481020141090   addons.xpi      DEBUG   Calling bootstrap method startup on firefox@getpocket.com version 1.0.5
1481020141091   addons.xpi      DEBUG   Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\webcompat@mozilla.org.xpi
1481020141091   addons.xpi      DEBUG   Calling bootstrap method startup on webcompat@mozilla.org version 1.0
1481020141093   addons.manager  DEBUG   Registering shutdown blocker for XPIProvider
1481020141093   addons.manager  DEBUG   Provider finished startup: XPIProvider
1481020141093   addons.manager  DEBUG   Starting provider: LightweightThemeManager
1481020141094   addons.manager  DEBUG   Registering shutdown blocker for LightweightThemeManager
1481020141094   addons.manager  DEBUG   Provider finished startup: LightweightThemeManager
1481020141094   addons.manager  DEBUG   Starting provider: GMPProvider
1481020141100   addons.manager  DEBUG   Registering shutdown blocker for GMPProvider
1481020141101   addons.manager  DEBUG   Provider finished startup: GMPProvider
1481020141101   addons.manager  DEBUG   Starting provider: PluginProvider
1481020141101   addons.manager  DEBUG   Registering shutdown blocker for PluginProvider
1481020141101   addons.manager  DEBUG   Provider finished startup: PluginProvider
1481020141102   addons.manager  DEBUG   Completed startup sequence
[GFX1]: Potential driver version mismatch ignored due to missing DLLs 0.0.0.0 and 0.0.0.0
1481020141564   addons.manager  DEBUG   Starting provider: <unnamed-provider>
1481020141564   addons.manager  DEBUG   Registering shutdown blocker for <unnamed-provider>
1481020141564   addons.manager  DEBUG   Provider finished startup: <unnamed-provider>
1481020141566   DeferredSave.extensions.json    DEBUG   Starting write
1481020141730   addons.repository       DEBUG   No addons.json found.
1481020141730   DeferredSave.addons.json        DEBUG   Save changes
1481020141733   DeferredSave.addons.json        DEBUG   Starting timer
1481020141777   addons.manager  DEBUG   Starting provider: PreviousExperimentProvider
1481020141777   addons.manager  DEBUG   Registering shutdown blocker for PreviousExperimentProvider
1481020141777   addons.manager  DEBUG   Provider finished startup: PreviousExperimentProvider
1481020141779   DeferredSave.extensions.json    DEBUG   Write succeeded
1481020141779   addons.xpi-utils        DEBUG   XPI Database saved, setting schema version preference to 17
1481020141807   DeferredSave.addons.json        DEBUG   Starting write
1481020141818   DeferredSave.addons.json        DEBUG   Write succeeded
Crash Annotation GraphicsCriticalError: |[C0][GFX1]: Potential driver version mismatch ignored due to missing DLLs 0.0.0.0 and 0.0.0.0 (t=0.565463) [GFX1]: Potential driver version mismatch ignored due to missing DLLs 0.0.0.0 and 0.0.0.0

Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'DESKTOP-09H92E8', ip: '192.168.1.184', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_111'
Driver info: driver.version: FirefoxDriver
        at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:125)
        at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:271)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:119)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:216)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:211)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:207)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:120)
        at website.automate.jwebrobot.executor.WebDriverProvider.createInstance(WebDriverProvider.java:15)
        at website.automate.jwebrobot.executor.DefaultScenarioExecutor.execute(DefaultScenarioExecutor.java:86)
        at website.automate.jwebrobot.executor.DefaultScenarioExecutor.execute(DefaultScenarioExecutor.java:71)
        at website.automate.jwebrobot.JWebRobot.run(JWebRobot.java:37)
        at website.automate.jwebrobot.JWebRobot.main(JWebRobot.java:54)
Caused by: org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","installDate":1479746003357,"updateDate":1479746003357,"applyBackgroundUpdates":1,"skinnable":true,"size":21146,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"50.0","maxVersion":"50.0"}],"targetPlatforms":[],"seen":true}
1481020141083   addons.xpi      DEBUG   getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1481020141083   DeferredSave.extensions.json    DEBUG   Save changes
1481020141083   addons.xpi      DEBUG   Updating database with changes to installed add-ons
1481020141083   addons.xpi-utils        DEBUG   Updating add-on states
1481020141085   addons.xpi-utils        DEBUG   Writing add-ons list
1481020141088   addons.xpi      DEBUG   Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\aushelper@mozilla.org.xpi
1481020141088   addons.xpi      DEBUG   Calling bootstrap method startup on aushelper@mozilla.org version 1.0
1481020141089   addons.xpi      DEBUG   Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1481020141089   addons.xpi      DEBUG   Calling bootstrap method startup on e10srollout@mozilla.org version 1.5
1481020141090   addons.xpi      DEBUG   Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1481020141090   addons.xpi      DEBUG   Calling bootstrap method startup on firefox@getpocket.com version 1.0.5
1481020141091   addons.xpi      DEBUG   Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\webcompat@mozilla.org.xpi
1481020141091   addons.xpi      DEBUG   Calling bootstrap method startup on webcompat@mozilla.org version 1.0
1481020141093   addons.manager  DEBUG   Registering shutdown blocker for XPIProvider
1481020141093   addons.manager  DEBUG   Provider finished startup: XPIProvider
1481020141093   addons.manager  DEBUG   Starting provider: LightweightThemeManager
1481020141094   addons.manager  DEBUG   Registering shutdown blocker for LightweightThemeManager
1481020141094   addons.manager  DEBUG   Provider finished startup: LightweightThemeManager
1481020141094   addons.manager  DEBUG   Starting provider: GMPProvider
1481020141100   addons.manager  DEBUG   Registering shutdown blocker for GMPProvider
1481020141101   addons.manager  DEBUG   Provider finished startup: GMPProvider
1481020141101   addons.manager  DEBUG   Starting provider: PluginProvider
1481020141101   addons.manager  DEBUG   Registering shutdown blocker for PluginProvider
1481020141101   addons.manager  DEBUG   Provider finished startup: PluginProvider
1481020141102   addons.manager  DEBUG   Completed startup sequence
[GFX1]: Potential driver version mismatch ignored due to missing DLLs 0.0.0.0 and 0.0.0.0
1481020141564   addons.manager  DEBUG   Starting provider: <unnamed-provider>
1481020141564   addons.manager  DEBUG   Registering shutdown blocker for <unnamed-provider>
1481020141564   addons.manager  DEBUG   Provider finished startup: <unnamed-provider>
1481020141566   DeferredSave.extensions.json    DEBUG   Starting write
1481020141730   addons.repository       DEBUG   No addons.json found.
1481020141730   DeferredSave.addons.json        DEBUG   Save changes
1481020141733   DeferredSave.addons.json        DEBUG   Starting timer
1481020141777   addons.manager  DEBUG   Starting provider: PreviousExperimentProvider
1481020141777   addons.manager  DEBUG   Registering shutdown blocker for PreviousExperimentProvider
1481020141777   addons.manager  DEBUG   Provider finished startup: PreviousExperimentProvider
1481020141779   DeferredSave.extensions.json    DEBUG   Write succeeded
1481020141779   addons.xpi-utils        DEBUG   XPI Database saved, setting schema version preference to 17
1481020141807   DeferredSave.addons.json        DEBUG   Starting write
1481020141818   DeferredSave.addons.json        DEBUG   Write succeeded
Crash Annotation GraphicsCriticalError: |[C0][GFX1]: Potential driver version mismatch ignored due to missing DLLs 0.0.0.0 and 0.0.0.0 (t=0.565463) [GFX1]: Potential driver version mismatch ignored due to missing DLLs 0.0.0.0 and 0.0.0.0

        at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:113)
        ... 11 more
```

**Comment by dimw** [comment]
@sbathke Sorry for the late response. It seems like Selenium 2.53.1 which is currently used in JWebRobot is incompatible to the current Firefox ([probably version >= 47.0](http://stackoverflow.com/a/38071659)). Unfortunately, latest Selenium 3.0.1 in conjunction with [geckodriver](https://github.com/mozilla/geckodriver/releases) does not work as well causing [geckodriver/firefox issues](http://stackoverflow.com/questions/39196419/abort-aborting-on-channel-error-line-2076-in-selenium-3-0-0-beta-2):

```
[Child 11040] ###!!! ABORT: Aborting on channel error.: file [...]/build/src/ipc/glue/MessageChannel.cpp, line 2056
```

Please consider to downgrade your installation in case you have to test with Firefox until the compatibility issue is fixed. Otherwise use Chrome.

**Comment by dimw** [comment]
[Except of missing browsers console logs](https://github.com/SeleniumHQ/selenium/issues/2910), the current Selenium 3.40 seems to work fine with the latest Firefox 54.

In general, the following combinations were verified on Windows:

| Browser | Version | WebDriver |
|----------|----------|----------------------|
| Chrome | 59.0.3071.115 | [2.30](http://chromedriver.storage.googleapis.com/index.html?path=2.30/) |
| Firefox | 54.0.1 | [v0.17.0](https://github.com/mozilla/geckodriver/releases) |
| Opera | 46.0.2597.39 | [2.29](https://github.com/operasoftware/operachromiumdriver/releases) |

I would suggest to update since having latest browser version is more important than having the console logs in all browsers.
